### ISSUE TITLE
"num" value seems not used

### ISSUE THREAD

**Issue by federico77** [endroid/PredictionIO#3]
Hello,
I am using Prediction 0.9.5 with Universal Recommender 0.2.3 and I just spotted something that I believe is an issue related to the "num" parameter. Doing REST calls like the following:

`curl -H "Content-Type: application/json" -d '{ "user": "1", "num": 40 }' http://localhost:8000/queries.json`
... smoothly returns 40 recommendations for user 1.

Doing the same with your getRecommendedItems() or getSimilarItems() seems to fall back to the UR engine defaults as if "num" was not considered at all.

For example:
`$items = $engineClient->getRecommendedItems(1, 40);`
... only returns 20 items as per my current engine.json setting.

Am I the only one experiencing it? Can you please help me?

Best regards,
Federico

**Comment by federico77** [comment]
Well, found the reason why it did not work... hope it will help someone to know that I was passing a string variable and it was silently bounced by the underlying SDK or Guzzle.

To have the parameter correctly set and used i had to provide an integer instead.

Regards,
Federico

**Comment by endroid** [comment]
Hi @federico77 thanks for your input. I added an explicit cast to integer for the num parameter in 2.0.5.
